### ISSUE TITLE
live data api

### ISSUE THREAD

**Issue by h3tz** [robiningelbrecht/wca-rest-api#1]
Hi there. Let's support each other: https://github.com/h3tz/wca-api

**Comment by robiningelbrecht** [comment]
How will you provide live data if WCA does not support this?

**Comment by h3tz** [comment]
> How will you provide live data if WCA does not support this?

just scrape!?

**Comment by robiningelbrecht** [comment]
Don't think WCA will like this tbh

**Comment by h3tz** [comment]
> Don't think WCA will like this tbh

i did not find something in TOS. I will discuss this with the swiss delegates at the next comp
