### ISSUE TITLE
Get number of records in person's schema

### ISSUE THREAD

**Issue by ViniRoveri** [robiningelbrecht/wca-rest-api#10]
It would be really nice if there was a way to get the number of records a person has beaten, just like there is the medals object in the person's schema.

This info is shown in the person's wca profile (as in the print below), so I am guessing it is somewhere in the database export and can be brought to the api as well

![image](https://github.com/robiningelbrecht/wca-rest-api/assets/111077051/bf66ee70-ee1b-45bd-9698-141025b2ae6e)

**Comment by robiningelbrecht** [comment]
Sadly, this data is not available in the database export

**Comment by ViniRoveri** [comment]
Oh yep, I just took a look at it and they unfortunately don't.

But, I just figured the way they get this info to show up on screen, and they use the "regionalSingleRecord" and "regionalAverageRecord" fields of the "Results" table.
These fields can be something like "NR" | "CR" | "WR" | null, and indicate the type of record that given result broke. So to take that to the front-end they just count the amount of each record.

The easiest way I can see it working on the api is just bringing these "regionalSingleRecord" and "regionalAverageRecord" fields to the Results schema just like the actual database, what do you think?

**Comment by robiningelbrecht** [comment]
Well, if the data is there, I could do both
- add the records to the person entity
- add possible record tags to the result entity

**Comment by robiningelbrecht** [comment]
@ViniRoveri What do you think, the person entity:
<img width="362" alt="image" src="https://github.com/robiningelbrecht/wca-rest-api/assets/203894/cfa0dd2a-667e-43ee-b182-d19a4a32a40d">

**Comment by ViniRoveri** [comment]
> @ViniRoveri What do you think, the person entity: <img alt="image" width="362" src="https://private-user-images.githubusercontent.com/203894/323599498-cfa0dd2a-667e-43ee-b182-d19a4a32a40d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDMwOTEsIm5iZiI6MTcxMzQ0Mjc5MSwicGF0aCI6Ii8yMDM4OTQvMzIzNTk5NDk4LWNmYTBkZDJhLTY2N2UtNDNlZS1iMTgyLWQxOWE0YTMyYTQwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMjE5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzFkZThmNzFhMDA3NzAzZThkMzY2YmRjMzE0NGUwYzA1MmFmMzU4ZWI5NzQ2MDVkY2Y3ODJiMDIwNjdlNzE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.69U9vF-SH_Sf4ck2iqOJ7j7PIE5Z2IEMZaddFqj3gK8">


Great man, really nice work!

By the way, just to help you a bit, the way they get if a result was a CR independently of the person's country is by:
```
regionalSingleRecord != 'WR' && regionalSingleRecord != 'NR' && regionalSingleRecord != null
```
Not the cleanest of codes, but it works lol

Thank you so much again for the work bro, the api really is great!

**Comment by ViniRoveri** [comment]
I'm developing a site that showcases historic data about brazillian cubing! The records, the championships, the GOATs, etc

**Comment by robiningelbrecht** [comment]
> I'm developing a site that showcases historic data about brazillian cubing! The records, the championships, the GOATs, etc

Cool, let me know when it is ready!
