### ISSUE TITLE
Last API builds failed (database download / unzip)

### ISSUE THREAD

**Issue by AnnikaStein** [robiningelbrecht/wca-rest-api#12]
The last three API builds resulted in an error, during the same step (unzipping the wca database file). Compared to previous builds, the download already looks incomplete.

Some new WCA IDs are eager to see their results reflected on a website pulling the info from the unofficial API (https://github.com/AnnikaStein/WCA-German-State-Ranks). And we would be happy to have the latest database version included in your api. 

Thanks a lot for your work! :)

**Comment by robiningelbrecht** [comment]
Issue seems to fixed, pipeline is running

**Comment by AnnikaStein** [comment]
Thank you 🙏
