### ISSUE TITLE
Getting images using id

### ISSUE THREAD

**Issue by Mankifg** [robiningelbrecht/wca-rest-api#2]
Hi, I really like your project, and I'm using it to make a discord bot. And I noticed that on [Max parks](https://www.worldcubeassociation.org/persons/2012PARK03) there is also an image (wow) but I noticed that image is following a weird structure:

[image](https://avatars.worldcubeassociation.org/uploads/user/avatar/2012PARK03/1631071192.jpg)

https://avatars.worldcubeassociation.org/uploads/user/avatar/2012PARK03/1631071192.jpg

and I don't understand why there is **1631071192** at the end and i think you may know. I think it can be countered in the order the image is  uploaded. But I don't know how to get that with a code. And do you know?

Thanks

**Comment by robiningelbrecht** [comment]
I think this is a randomly genereted id, but will need to check to be sure

**Comment by Mankifg** [comment]
ok, but are you 100% sure, because i looked at some profiles and they tend to be 15xxx or 16xxx ? and any idea how to extract them?

**Comment by Mankifg** [comment]
so i figured out a solution to use bs4 and scrape site and just ping me if you want code
