### ISSUE TITLE
decoding 3x3 mbf

### ISSUE THREAD

**Issue by Mankifg** [robiningelbrecht/wca-rest-api#3]
how am i supposed to decode `940239001`
 to `6/7 39:50` and its a 3x3 multi blindfold result
thanks and lmk if you nead additional info

**Comment by LeonardoSDT** [comment]
You can find the instructions to do that here:

https://www.worldcubeassociation.org/export/results

**Comment by robiningelbrecht** [comment]
Indeed, thanks for referencing
