### ISSUE TITLE
Medals Counter

### ISSUE THREAD

**Issue by XNizi** [robiningelbrecht/wca-rest-api#6]
The medal counter shows the number of places won in all rounds in all tournaments (I also checked with other users, and it's probably true) It seems to me that this should only return the value of the final rounds
![Screenshot_3](https://github.com/robiningelbrecht/wca-rest-api/assets/48836987/b6302712-ec46-452e-8240-1be0177ae12c)
![Screenshot_4](https://github.com/robiningelbrecht/wca-rest-api/assets/48836987/7d7eae8e-daff-4456-9243-b341e415eab4)

**Comment by robiningelbrecht** [comment]
Hi @XNizi , thanks for reporting this. Adding a fix as we speak ;)
This should be fixed tomorrow when the new API build has run

**Comment by robiningelbrecht** [comment]
@XNizi seems to be solved:
![image](https://github.com/robiningelbrecht/wca-rest-api/assets/203894/9a1d0723-79ef-4583-986b-037d53aa0dea)

Thank you so much for reporting this and looking into this.
Feel free to open new bug tickets or feature requests if needed
