### ISSUE TITLE
Build API is failing

### ISSUE THREAD

**Issue by castus** [robiningelbrecht/wca-rest-api#8]
Hi @robiningelbrecht ,

I've noticed that Build API is failing for some time. Could you please take a look?
Example pipeline: https://github.com/robiningelbrecht/wca-rest-api/actions/runs/7873774609/job/21481868328

**Comment by robiningelbrecht** [comment]
I think WCA blocked GitHub's ip address. I'll need to contact them :)

**Comment by robiningelbrecht** [comment]
Should be fixed

**Comment by castus** [comment]
Thanks! What was the reason?

**Comment by robiningelbrecht** [comment]
Url to the export cfile changed and my CURL command didn't follow redirects

**Comment by robiningelbrecht** [comment]
Btw, are you using this api for a project? If so, can I know which one?

**Comment by castus** [comment]
Yes, I scrap some data using your API. The project is here https://github.com/castus/speedcube-events and the frontend is here https://kalendarz.krzysztofromanowski.pl (Polish lang only).
